package com.sw.view;

/**
 *
 * @author Me
 */
public class AcercaDe extends javax.swing.JFrame
{

    /**
     * Creates new form AcercaDe
     */
    public AcercaDe()
    {

        initWindow();

        initComponents();
    }

    private void initWindow()
    {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            System.out.println(ex.getMessage());
        }
        //</editor-fold>

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        programadoresLabel = new javax.swing.JLabel();
        integrantes = new javax.swing.JLabel();
        integrantes1 = new javax.swing.JLabel();
        integrantes2 = new javax.swing.JLabel();
        derechos = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Acerca de...");
        setMaximumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        programadoresLabel.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        programadoresLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        programadoresLabel.setText("PROGRAMADORES");
        getContentPane().add(programadoresLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        integrantes.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        integrantes.setText("3. Cauich Dávalos Víctor");
        integrantes.setToolTipText("");
        getContentPane().add(integrantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 330, 40));

        integrantes1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        integrantes1.setText("1. Canto Dzul Guillermo");
        integrantes1.setToolTipText("");
        getContentPane().add(integrantes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 330, 40));

        integrantes2.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        integrantes2.setText("2. Canul Ibarra Nicolás");
        integrantes2.setToolTipText("");
        getContentPane().add(integrantes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 330, 40));

        derechos.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        derechos.setText("Programación orientada a objetos");
        getContentPane().add(derechos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        fondo.setForeground(new java.awt.Color(204, 51, 0));
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/fondo.jpg"))); // NOI18N
        fondo.setMaximumSize(new java.awt.Dimension(400, 300));
        fondo.setMinimumSize(new java.awt.Dimension(400, 300));
        fondo.setPreferredSize(new java.awt.Dimension(400, 300));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel derechos;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel integrantes;
    private javax.swing.JLabel integrantes1;
    private javax.swing.JLabel integrantes2;
    private javax.swing.JLabel programadoresLabel;
    // End of variables declaration//GEN-END:variables
}
