package com.sw.view;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Mohammed
 */
public class AnadirTipoPrendaInterfaz extends javax.swing.JFrame
{

    /**
     * Creates new form AnadirTipoPrenda
     */
    public AnadirTipoPrendaInterfaz()
    {

        initWindow();

        initComponents();

    }

    private void initWindow()
    {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            System.out.println(ex.getMessage());
        }
        //</editor-fold>

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        title = new javax.swing.JLabel();
        tipoPrendaLabel = new javax.swing.JLabel();
        entradaTipoPrenda = new javax.swing.JTextField();
        anadirTipoPrenda = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Añadir tipo de prenda");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/addPrendasTitle.png"))); // NOI18N
        title.setText("Añadir un tipo de prenda");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 340, 50));

        tipoPrendaLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tipoPrendaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tipoPrendaLabel.setText("Tipo de prenda:");
        tipoPrendaLabel.setMaximumSize(new java.awt.Dimension(120, 30));
        tipoPrendaLabel.setMinimumSize(new java.awt.Dimension(120, 30));
        tipoPrendaLabel.setPreferredSize(new java.awt.Dimension(120, 30));
        getContentPane().add(tipoPrendaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 180, -1));

        entradaTipoPrenda.setMaximumSize(new java.awt.Dimension(120, 30));
        entradaTipoPrenda.setMinimumSize(new java.awt.Dimension(120, 30));
        entradaTipoPrenda.setPreferredSize(new java.awt.Dimension(120, 30));
        getContentPane().add(entradaTipoPrenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 160, -1));

        anadirTipoPrenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/add.png"))); // NOI18N
        anadirTipoPrenda.setActionCommand("add");
        anadirTipoPrenda.setMaximumSize(new java.awt.Dimension(80, 40));
        anadirTipoPrenda.setMinimumSize(new java.awt.Dimension(80, 40));
        anadirTipoPrenda.setPreferredSize(new java.awt.Dimension(80, 40));
        getContentPane().add(anadirTipoPrenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getAnadirTipoPrenda()
    {
        return anadirTipoPrenda;
    }

    public JTextField getEntradaTipoPrenda()
    {
        return entradaTipoPrenda;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anadirTipoPrenda;
    private javax.swing.JTextField entradaTipoPrenda;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel tipoPrendaLabel;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
