package com.sw.view;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author Mohammed
 */
public class AnadirPrendaInterfaz extends javax.swing.JFrame
{

    public AnadirPrendaInterfaz()
    {
        initWindow();

        initComponents();

    }

    private void initWindow()
    {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            System.out.println(ex.getMessage());
        }
        //</editor-fold>

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        prendaTitle = new javax.swing.JLabel();
        prendaLabel = new javax.swing.JLabel();
        cantidadLabel = new javax.swing.JLabel();
        tipoPrendaLabel = new javax.swing.JLabel();
        ok = new javax.swing.JButton();
        cantidad = new javax.swing.JTextField();
        prenda = new javax.swing.JTextField();
        tiposPrenda = new javax.swing.JComboBox<>();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Añadir prenda");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prendaTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        prendaTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prendaTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/addPrendasTitle.png"))); // NOI18N
        prendaTitle.setText("Añadir prenda");
        getContentPane().add(prendaTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 320, -1));

        prendaLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        prendaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        prendaLabel.setText("Prenda:");
        prendaLabel.setMaximumSize(new java.awt.Dimension(110, 30));
        prendaLabel.setMinimumSize(new java.awt.Dimension(110, 30));
        prendaLabel.setPreferredSize(new java.awt.Dimension(110, 30));
        getContentPane().add(prendaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        cantidadLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cantidadLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cantidadLabel.setText("Cantidad:");
        cantidadLabel.setMaximumSize(new java.awt.Dimension(110, 30));
        cantidadLabel.setMinimumSize(new java.awt.Dimension(110, 30));
        cantidadLabel.setPreferredSize(new java.awt.Dimension(110, 30));
        getContentPane().add(cantidadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        tipoPrendaLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tipoPrendaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tipoPrendaLabel.setText("Tipo de prenda:");
        tipoPrendaLabel.setMaximumSize(new java.awt.Dimension(110, 30));
        tipoPrendaLabel.setMinimumSize(new java.awt.Dimension(110, 30));
        tipoPrendaLabel.setPreferredSize(new java.awt.Dimension(110, 30));
        getContentPane().add(tipoPrendaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/add.png"))); // NOI18N
        ok.setMaximumSize(new java.awt.Dimension(90, 40));
        ok.setMinimumSize(new java.awt.Dimension(90, 40));
        ok.setPreferredSize(new java.awt.Dimension(90, 40));
        getContentPane().add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 240, -1, -1));

        cantidad.setMaximumSize(new java.awt.Dimension(190, 30));
        cantidad.setMinimumSize(new java.awt.Dimension(190, 30));
        cantidad.setPreferredSize(new java.awt.Dimension(190, 30));
        getContentPane().add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        prenda.setMaximumSize(new java.awt.Dimension(190, 30));
        prenda.setMinimumSize(new java.awt.Dimension(190, 30));
        prenda.setPreferredSize(new java.awt.Dimension(190, 30));
        getContentPane().add(prenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        tiposPrenda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Camisa", "Playera", "Ropa interior", "Sábana" }));
        tiposPrenda.setMaximumSize(new java.awt.Dimension(190, 30));
        tiposPrenda.setMinimumSize(new java.awt.Dimension(190, 30));
        tiposPrenda.setPreferredSize(new java.awt.Dimension(190, 30));
        getContentPane().add(tiposPrenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTextField getCantidad()
    {
        return cantidad;
    }

    public void setCantidad(JTextField cantidad)
    {
        this.cantidad = cantidad;
    }

    public JButton getOk()
    {
        return ok;
    }

    public void setOk(JButton ok)
    {
        this.ok = ok;
    }

    public JTextField getPrenda()
    {
        return prenda;
    }

    public void setPrenda(JTextField prenda)
    {
        this.prenda = prenda;
    }

    public JComboBox<String> getTiposPrenda()
    {
        return tiposPrenda;
    }

    public void setTiposPrenda(JComboBox<String> tiposPrenda)
    {
        this.tiposPrenda = tiposPrenda;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantidad;
    private javax.swing.JLabel cantidadLabel;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton ok;
    private javax.swing.JTextField prenda;
    private javax.swing.JLabel prendaLabel;
    private javax.swing.JLabel prendaTitle;
    private javax.swing.JLabel tipoPrendaLabel;
    private javax.swing.JComboBox<String> tiposPrenda;
    // End of variables declaration//GEN-END:variables
}
