package com.sw.view;

import javax.swing.JTextField;

/**
 *
 * @author Mohammed
 */
public class AñadirNuevoCliente extends javax.swing.JFrame
{

    public AñadirNuevoCliente()
    {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        registrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        correo = new javax.swing.JTextField();
        nombreValido = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Añadir a nuevo cliente");
        setMaximumSize(new java.awt.Dimension(550, 400));
        setMinimumSize(new java.awt.Dimension(550, 400));
        setPreferredSize(new java.awt.Dimension(550, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/anadirClienteTitle.png"))); // NOI18N
        jLabel1.setText("Añadir cliente ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel2.setText("Teléfono:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 211, -1, 33));

        jLabel7.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel7.setText("Nombre completo:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 132, -1, 33));

        jLabel9.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel9.setText("Dirección:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 251, -1, 33));

        nombre.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        nombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nombre.setToolTipText("Nombre del cliente");
        nombre.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                nombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                nombreFocusLost(evt);
            }
        });
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 133, 194, 33));

        direccion.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        direccion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        direccion.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                direccionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                direccionFocusLost(evt);
            }
        });
        getContentPane().add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 252, 194, 33));

        telefono.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        telefono.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        telefono.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                telefonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                telefonoFocusLost(evt);
            }
        });
        getContentPane().add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 212, 194, 33));

        registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/add.png"))); // NOI18N
        registrar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                registrarActionPerformed(evt);
            }
        });
        getContentPane().add(registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 127, 40));

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Correo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 174, 90, 26));

        correo.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        correo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        correo.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                correoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                correoFocusLost(evt);
            }
        });
        getContentPane().add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 172, 194, 33));

        nombreValido.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        nombreValido.setText("   ");
        getContentPane().add(nombreValido, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 142, 90, -1));

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jLabel4.setText("   ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 181, -1, -1));

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jLabel5.setText("   ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 221, -1, -1));

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jLabel6.setText("   ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 261, -1, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_registrarActionPerformed
    {//GEN-HEADEREND:event_registrarActionPerformed

    }//GEN-LAST:event_registrarActionPerformed

    private void nombreFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_nombreFocusGained
    {//GEN-HEADEREND:event_nombreFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreFocusGained

    private void nombreFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_nombreFocusLost
    {//GEN-HEADEREND:event_nombreFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreFocusLost

    private void telefonoFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_telefonoFocusGained
    {//GEN-HEADEREND:event_telefonoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoFocusGained

    private void telefonoFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_telefonoFocusLost
    {//GEN-HEADEREND:event_telefonoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoFocusLost

    private void direccionFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_direccionFocusGained
    {//GEN-HEADEREND:event_direccionFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionFocusGained

    private void direccionFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_direccionFocusLost
    {//GEN-HEADEREND:event_direccionFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionFocusLost

    private void correoFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_correoFocusGained
    {//GEN-HEADEREND:event_correoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_correoFocusGained

    private void correoFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_correoFocusLost
    {//GEN-HEADEREND:event_correoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_correoFocusLost

    public JTextField getEspecialidad()
    {
        return telefono;
    }

    public JTextField getMatricula()
    {
        return nombre;
    }

    public JTextField getNombre()
    {
        return direccion;
    }

    public static void main(String[] args)
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());

                    break;
                }

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            System.out.println(ex.getMessage());
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
        {
            AñadirNuevoCliente agregarMaestro = new AñadirNuevoCliente();

            agregarMaestro.setVisible(true);
            agregarMaestro.setLocationRelativeTo(null);

        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField correo;
    private javax.swing.JTextField direccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nombre;
    private javax.swing.JLabel nombreValido;
    private javax.swing.JButton registrar;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
