package com.sw.view;

import com.sw.controller.CellRenderer;
import com.sw.controller.ComboRenderer;
import com.sw.controller.ComboRenderer.ComboItem;
import com.sw.controller.TableHeaderRenderer;
import com.sw.controller.TableManager;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionListener;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Mohammed
 */
public class Clientes extends javax.swing.JFrame
{

    private CellRenderer cellRenderer;

    public Clientes()
    {
        initMyComponents();

        initComponents();

        initTable();

        loadComboModel();

    }

    private void initMyComponents()
    {
        verHistorial = new ArrayList<>();

        for (int i = 0; i < 5; i++)
            verHistorial.add(new JButton(new ImageIcon(getClass().getResource("/com/src/images/historial.png"))));

        cellRenderer = new CellRenderer();

    }

    private void initTable()
    {

        clientes.setDefaultRenderer(Object.class, cellRenderer);
        JTableHeader jTableHeader = clientes.getTableHeader();
        jTableHeader.setDefaultRenderer(new TableHeaderRenderer());
        clientes.setTableHeader(jTableHeader);

        clientes.addMouseMotionListener(new MouseMotionListener()
        {
            @Override
            public void mouseDragged(MouseEvent e)
            {

            }

            @Override
            public void mouseMoved(MouseEvent e)
            {

                cellRenderer.setMouseX(e.getX());
                cellRenderer.setMouseY(e.getY());

            }

        });

        Object[][] items = new Object[5][6];

        clientes.setModel(new DefaultTableModel(new TableManager().getItems(items, verHistorial, 5), new String[]
        {

            "Nombre", "Correo", "Teléfono", "Dirección", "N° servicios", "Ver historial"

        }));

        clientes.setName("Clientes");

    }

    private void loadComboModel()
    {
        ordenarPor.setRenderer(new ComboRenderer());
        ordenarPor.setModel(loadComboItems());

    }

    private DefaultComboBoxModel<ComboItem> loadComboItems()
    {
        DefaultComboBoxModel<ComboItem> dm = new DefaultComboBoxModel<>();

        dm.addElement(new ComboItem(new ImageIcon(getClass().getResource("/com/src/images/name.png")), "Nombre"));

        dm.addElement(new ComboItem(new ImageIcon(getClass().getResource("/com/src/images/numbers.png")), "N° de servicios"));

        return dm;

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panelClientes = new javax.swing.JScrollPane();
        clientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ordenarPor = new javax.swing.JComboBox<>();
        anadirCliente = new javax.swing.JButton();
        modificarCliente = new javax.swing.JButton();
        eliminarCliente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clientes registrados");
        setMaximumSize(new java.awt.Dimension(925, 710));
        setMinimumSize(new java.awt.Dimension(925, 710));
        setPreferredSize(new java.awt.Dimension(925, 710));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelClientes.setToolTipText("");
        panelClientes.setMaximumSize(new java.awt.Dimension(905, 550));
        panelClientes.setMinimumSize(new java.awt.Dimension(905, 550));
        panelClientes.setPreferredSize(new java.awt.Dimension(905, 550));

        clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null, verHistorial},
                {null, null, null, null, null, verHistorial},
                {null, null, null, null, null, verHistorial},
                {null, null, null, null, null, verHistorial},
                {null, null, null, null, null, verHistorial},
                {null, null, null, null, null, verHistorial},
                {null, null, null, null, null, verHistorial}

            },
            new String []
            {
                "Nombre", "Correo", "Teléfono", "Dirección", "N° servicios", "Ver historial"
            }

        ));
        panelClientes.setViewportView(clientes);

        getContentPane().add(panelClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 919, 530));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/clienteTitle.png"))); // NOI18N
        jLabel1.setText("Clientes Registrados");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 70));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ordenar por:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 25));

        ordenarPor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ordenarPor.setToolTipText("Ordenar por...");
        ordenarPor.setMaximumSize(new java.awt.Dimension(125, 25));
        ordenarPor.setMinimumSize(new java.awt.Dimension(125, 25));
        ordenarPor.setPreferredSize(new java.awt.Dimension(125, 25));
        getContentPane().add(ordenarPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        anadirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/add.png"))); // NOI18N
        anadirCliente.setText("Añadir cliente");
        anadirCliente.setToolTipText("Añadir cliente");
        anadirCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(anadirCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 130, 30));

        modificarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/edit.png"))); // NOI18N
        modificarCliente.setText("Modificar cliente");
        modificarCliente.setToolTipText("Modificar cliente");
        modificarCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        modificarCliente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                modificarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(modificarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 50, 130, 30));

        eliminarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/delete.png"))); // NOI18N
        eliminarCliente.setText("Eliminar cliente");
        eliminarCliente.setToolTipText("Eliminar a un cliente");
        eliminarCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(eliminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, 130, 30));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/logo.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 230, 95));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/fondo.jpg"))); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(925, 710));
        jLabel4.setMinimumSize(new java.awt.Dimension(925, 710));
        jLabel4.setPreferredSize(new java.awt.Dimension(925, 710));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 920, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificarClienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_modificarClienteActionPerformed
    {//GEN-HEADEREND:event_modificarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
        {

            Clientes clientes = new Clientes();

            clientes.setVisible(true);
            clientes.setLocationRelativeTo(null);

        });

    }

    private ArrayList<JButton> verHistorial;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anadirCliente;
    private javax.swing.JTable clientes;
    private javax.swing.JButton eliminarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton modificarCliente;
    private javax.swing.JComboBox<ComboItem> ordenarPor;
    private javax.swing.JScrollPane panelClientes;
    // End of variables declaration//GEN-END:variables

}
