package com.sw.view;

/**
 *
 * @author Mohammed
 */
public class Configuracion extends javax.swing.JFrame
{

    public Configuracion()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        tiltleLabel = new javax.swing.JLabel();
        precioLabel = new javax.swing.JLabel();
        precio = new javax.swing.JTextField();
        precioValido = new javax.swing.JLabel();
        tiposLabel = new javax.swing.JLabel();
        tiposPrendas = new javax.swing.JButton();
        colorLabel = new javax.swing.JLabel();
        colorChooser = new javax.swing.JButton();
        ok = new javax.swing.JButton();
        ordenarPor = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configuración");
        setMaximumSize(new java.awt.Dimension(500, 370));
        setMinimumSize(new java.awt.Dimension(500, 370));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tiltleLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tiltleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/config.png"))); // NOI18N
        tiltleLabel.setText("Configuración");
        getContentPane().add(tiltleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        precioLabel.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        precioLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        precioLabel.setText("Precio por kg:");
        precioLabel.setToolTipText("");
        precioLabel.setMaximumSize(new java.awt.Dimension(140, 30));
        precioLabel.setMinimumSize(new java.awt.Dimension(140, 30));
        precioLabel.setPreferredSize(new java.awt.Dimension(140, 30));
        getContentPane().add(precioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 170, -1));

        precio.setMaximumSize(new java.awt.Dimension(140, 30));
        precio.setMinimumSize(new java.awt.Dimension(140, 30));
        precio.setPreferredSize(new java.awt.Dimension(140, 30));
        getContentPane().add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        precioValido.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        precioValido.setMaximumSize(new java.awt.Dimension(110, 30));
        precioValido.setMinimumSize(new java.awt.Dimension(110, 30));
        precioValido.setPreferredSize(new java.awt.Dimension(110, 30));
        getContentPane().add(precioValido, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        tiposLabel.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        tiposLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tiposLabel.setText("Tipos de prendas:");
        tiposLabel.setMaximumSize(new java.awt.Dimension(140, 30));
        tiposLabel.setMinimumSize(new java.awt.Dimension(140, 30));
        tiposLabel.setPreferredSize(new java.awt.Dimension(140, 30));
        getContentPane().add(tiposLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 170, -1));

        tiposPrendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/tshirt.png"))); // NOI18N
        tiposPrendas.setToolTipText("Añadir tipos de prendas");
        tiposPrendas.setMaximumSize(new java.awt.Dimension(90, 40));
        tiposPrendas.setMinimumSize(new java.awt.Dimension(90, 40));
        tiposPrendas.setPreferredSize(new java.awt.Dimension(90, 40));
        getContentPane().add(tiposPrendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        colorLabel.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        colorLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        colorLabel.setText("Color de las tablas:");
        colorLabel.setMaximumSize(new java.awt.Dimension(140, 30));
        colorLabel.setMinimumSize(new java.awt.Dimension(140, 30));
        colorLabel.setPreferredSize(new java.awt.Dimension(140, 30));
        getContentPane().add(colorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 170, -1));

        colorChooser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/color.png"))); // NOI18N
        colorChooser.setMaximumSize(new java.awt.Dimension(90, 40));
        colorChooser.setMinimumSize(new java.awt.Dimension(90, 40));
        colorChooser.setPreferredSize(new java.awt.Dimension(90, 40));
        getContentPane().add(colorChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/ok.png"))); // NOI18N
        ok.setMaximumSize(new java.awt.Dimension(90, 40));
        ok.setMinimumSize(new java.awt.Dimension(90, 40));
        ok.setPreferredSize(new java.awt.Dimension(90, 40));
        getContentPane().add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));

        ordenarPor.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        ordenarPor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ordenarPor.setText("Ordenar de forma:");
        ordenarPor.setMaximumSize(new java.awt.Dimension(140, 30));
        ordenarPor.setMinimumSize(new java.awt.Dimension(140, 30));
        ordenarPor.setPreferredSize(new java.awt.Dimension(140, 30));
        getContentPane().add(ordenarPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setMaximumSize(new java.awt.Dimension(140, 30));
        jComboBox1.setMinimumSize(new java.awt.Dimension(140, 30));
        jComboBox1.setPreferredSize(new java.awt.Dimension(140, 30));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {

            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            System.out.println(ex.getMessage());
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
        {
            Configuracion config = new Configuracion();

            config.setVisible(true);
            config.setLocationRelativeTo(null);

        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton colorChooser;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JLabel fondo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JButton ok;
    private javax.swing.JLabel ordenarPor;
    private javax.swing.JTextField precio;
    private javax.swing.JLabel precioLabel;
    private javax.swing.JLabel precioValido;
    private javax.swing.JLabel tiltleLabel;
    private javax.swing.JLabel tiposLabel;
    private javax.swing.JButton tiposPrendas;
    // End of variables declaration//GEN-END:variables
}
