package com.sw.view;

import com.sw.renderer.ComboRenderer.ComboItem;
import javax.swing.JButton;
import javax.swing.JComboBox;

/**
 *
 * @author Me
 */
public class EditarServicio extends javax.swing.JFrame
{

    public EditarServicio()
    {

        initWindow();

        initComponents();

    }

    private void initWindow()
    {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            System.out.println(ex.getMessage());
        }
        //</editor-fold>

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        title = new javax.swing.JLabel();
        clienteLabel = new javax.swing.JLabel();
        clientes = new javax.swing.JComboBox<>();
        ok = new javax.swing.JButton();
        verTicket = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/editarTitle.png"))); // NOI18N
        title.setText("Editar servicio");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        clienteLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        clienteLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        clienteLabel.setText("Cliente:");
        clienteLabel.setMaximumSize(new java.awt.Dimension(100, 30));
        clienteLabel.setMinimumSize(new java.awt.Dimension(100, 30));
        clienteLabel.setPreferredSize(new java.awt.Dimension(100, 30));
        getContentPane().add(clienteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        clientes.setModel(new javax.swing.DefaultComboBoxModel<>(new ComboItem[] { null }));
        clientes.setMaximumSize(new java.awt.Dimension(200, 30));
        clientes.setMinimumSize(new java.awt.Dimension(200, 30));
        clientes.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/ok.png"))); // NOI18N
        ok.setToolTipText("Ok");
        ok.setActionCommand("ok");
        ok.setMaximumSize(new java.awt.Dimension(80, 40));
        ok.setMinimumSize(new java.awt.Dimension(80, 40));
        ok.setPreferredSize(new java.awt.Dimension(80, 40));
        getContentPane().add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        verTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/ticket.png"))); // NOI18N
        verTicket.setToolTipText("Ver ticket");
        verTicket.setActionCommand("verTicket");
        verTicket.setMaximumSize(new java.awt.Dimension(80, 40));
        verTicket.setMinimumSize(new java.awt.Dimension(80, 40));
        verTicket.setPreferredSize(new java.awt.Dimension(80, 40));
        getContentPane().add(verTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JComboBox<ComboItem> getClientes()
    {
        return clientes;
    }

    public JButton getOk()
    {
        return ok;
    }

    public JButton getVerTicket()
    {
        return verTicket;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clienteLabel;
    private javax.swing.JComboBox<ComboItem> clientes;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton ok;
    private javax.swing.JLabel title;
    private javax.swing.JButton verTicket;
    // End of variables declaration//GEN-END:variables
}
