package com.sw.view;

import com.sw.renderer.ComboRenderer.ComboItem;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;

/**
 *
 * @author Me
 */
public class HistorialInterfaz extends javax.swing.JFrame
{

    public HistorialInterfaz()
    {
        initMyComponents();

        initComponents();

    }

    private void initWindow()
    {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            System.out.println(ex.getMessage());
        }
        //</editor-fold>

    }

    private void initMyComponents()
    {

        verPrendas = new ArrayList<>();
        verTicket = new ArrayList<>();
        eliminar = new ArrayList<>();

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        titleLabel = new javax.swing.JLabel();
        panelHistorial = new javax.swing.JScrollPane();
        historial = new javax.swing.JTable();
        ordenarPorLabel = new javax.swing.JLabel();
        ordenarPor = new javax.swing.JComboBox<>();
        logoLabel = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Historial");
        setMaximumSize(new java.awt.Dimension(915, 700));
        setMinimumSize(new java.awt.Dimension(915, 700));
        setPreferredSize(new java.awt.Dimension(915, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/historialTitle.png"))); // NOI18N
        titleLabel.setText("Historial de servicios");
        getContentPane().add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 300, 95));

        panelHistorial.setMaximumSize(new java.awt.Dimension(915, 520));
        panelHistorial.setMinimumSize(new java.awt.Dimension(915, 520));
        panelHistorial.setName(""); // NOI18N
        panelHistorial.setPreferredSize(new java.awt.Dimension(915, 520));

        historial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null, null},

            },
            new String []
            {
                null, null, null, null, null, null
            }

        ));
        panelHistorial.setViewportView(historial);

        getContentPane().add(panelHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        ordenarPorLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ordenarPorLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ordenarPorLabel.setText("Ordenar por:");
        getContentPane().add(ordenarPorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 112, -1, 25));

        ordenarPor.setModel(new javax.swing.DefaultComboBoxModel<>(new ComboItem[] {null}));
        getContentPane().add(ordenarPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 112, 125, 25));

        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/logo.jpg"))); // NOI18N
        getContentPane().add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 11, 215, 95));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public ArrayList<JButton> getVerPrendas()
    {
        return verPrendas;
    }

    public ArrayList<JButton> getEliminar()
    {
        return eliminar;
    }

    public ArrayList<JButton> getVerTicket()
    {
        return verTicket;
    }

    public JTable getTablaHistorial()
    {
        return historial;
    }

    public JComboBox<ComboItem> getOrdenarPor()
    {
        return ordenarPor;
    }

    private ArrayList<JButton> verPrendas;
    private ArrayList<JButton> verTicket;
    private ArrayList<JButton> eliminar;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JTable historial;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JComboBox<ComboItem> ordenarPor;
    private javax.swing.JLabel ordenarPorLabel;
    private javax.swing.JScrollPane panelHistorial;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
