package com.sw.view;

import com.sw.controller.TableManager;
import com.sw.renderer.ComboRenderer;
import com.sw.renderer.ComboRenderer.ComboItem;
import com.sw.utilities.Utilities;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mohammed
 */
public class Historial extends javax.swing.JFrame
{

    public Historial()
    {
        initMyComponents();

        initComponents();

        renderTable();

        loadComboModel();

    }

    private void initMyComponents()
    {

        eliminar = new ArrayList<>();
        verPrendas = new ArrayList<>();

        for (int i = 0; i < 5; i++)
        {

            eliminar.add(new JButton(Utilities.getIcon("/com/src/images/delete.png")));
            verPrendas.add(new JButton(Utilities.getIcon("/com/src/images/tshirt.png")));

        }

    }

    private void renderTable()
    {

        TableManager tableManager = new TableManager();

        tableManager.renderTableModel(historial, "Historial");

        Object[][] items = new Object[5][6];

        historial.setModel(new DefaultTableModel(tableManager.loadItems(items, new int[]
        {
            1, 5

        }, verPrendas, eliminar), new String[]
        {

            "Cliente", "Prendas", "Fecha", "Total kg.", "Precio total", "Eliminar"

        }));

    }

    private void loadComboModel()
    {
        ordenarPor.setRenderer(new ComboRenderer());
        ordenarPor.setModel(loadComboItems());
    }

    private DefaultComboBoxModel<ComboRenderer.ComboItem> loadComboItems()
    {
        DefaultComboBoxModel<ComboItem> dm = new DefaultComboBoxModel<>();

        dm.addElement(new ComboItem(Utilities.getIcon("/com/src/images/name.png"), "Nombre"));

        dm.addElement(new ComboItem(Utilities.getIcon("/com/src/images/fecha.png"), "Fecha"));

        return dm;

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        panelHistorial = new javax.swing.JScrollPane();
        historial = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        ordenarPor = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(915, 720));
        setMinimumSize(new java.awt.Dimension(915, 720));
        setPreferredSize(new java.awt.Dimension(915, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/historialTitle.png"))); // NOI18N
        jLabel1.setText("Historial de servicios");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 300, 95));

        panelHistorial.setMaximumSize(new java.awt.Dimension(910, 530));
        panelHistorial.setMinimumSize(new java.awt.Dimension(910, 530));
        panelHistorial.setPreferredSize(new java.awt.Dimension(910, 530));

        historial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null, null},

            },
            new String []
            {
                null, null, null, null, null, null
            }

        ));
        panelHistorial.setViewportView(historial);

        getContentPane().add(panelHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Ordenar por:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 112, -1, 25));

        ordenarPor.setModel(new javax.swing.DefaultComboBoxModel<>(new ComboItem[] {null}));
        getContentPane().add(ordenarPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 112, 125, 25));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/logo.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 11, 215, 95));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
        {
            Historial historial = new Historial();

            historial.setVisible(true);
            historial.setLocationRelativeTo(null);

        });

    }

    private ArrayList<JButton> eliminar;
    private ArrayList<JButton> verPrendas;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable historial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<ComboItem> ordenarPor;
    private javax.swing.JScrollPane panelHistorial;
    // End of variables declaration//GEN-END:variables
}
