package com.sw.view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Me
 */
public class NuevoCliente extends javax.swing.JFrame
{

    public NuevoCliente()
    {
        initWindow();

        initComponents();

    }

    private void initWindow()
    {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {

            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());

                    break;
                }

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            System.out.println(ex.getMessage());
        }
        //</editor-fold>

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        titleLabel = new javax.swing.JLabel();
        telefonoLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        direccionLabel = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        correoLabel = new javax.swing.JLabel();
        correo = new javax.swing.JTextField();
        nombreValidoLabel = new javax.swing.JLabel();
        correoValidoLabel = new javax.swing.JLabel();
        telefonoValidoLabel = new javax.swing.JLabel();
        direccionValidaLabel = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Añadir a nuevo cliente");
        setMinimumSize(new java.awt.Dimension(550, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setFont(new java.awt.Font("Consolas", 0, 36)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/anadirClienteTitle.png"))); // NOI18N
        titleLabel.setText("Añadir cliente ");
        getContentPane().add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        telefonoLabel.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        telefonoLabel.setText("Teléfono:");
        getContentPane().add(telefonoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 211, -1, 33));

        nombreLabel.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        nombreLabel.setText("Nombre completo:");
        getContentPane().add(nombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 132, -1, 33));

        direccionLabel.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        direccionLabel.setText("Dirección:");
        getContentPane().add(direccionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 251, -1, 33));

        nombre.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        nombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nombre.setToolTipText("Nombre del cliente");
        nombre.setMaximumSize(new java.awt.Dimension(195, 35));
        nombre.setMinimumSize(new java.awt.Dimension(195, 35));
        nombre.setPreferredSize(new java.awt.Dimension(195, 35));
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 133, -1, -1));

        direccion.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        direccion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        direccion.setToolTipText("Dirección del cliente");
        direccion.setMaximumSize(new java.awt.Dimension(195, 35));
        direccion.setMinimumSize(new java.awt.Dimension(195, 35));
        direccion.setPreferredSize(new java.awt.Dimension(195, 35));
        getContentPane().add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 252, -1, -1));

        telefono.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        telefono.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        telefono.setToolTipText("Teléfono del cliente");
        telefono.setMaximumSize(new java.awt.Dimension(195, 35));
        telefono.setMinimumSize(new java.awt.Dimension(195, 35));
        telefono.setPreferredSize(new java.awt.Dimension(195, 35));
        getContentPane().add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 212, -1, -1));

        ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/add.png"))); // NOI18N
        ok.setToolTipText("Añadir cliente");
        getContentPane().add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 127, 40));

        correoLabel.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        correoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        correoLabel.setText("Correo:");
        getContentPane().add(correoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 174, 90, 26));

        correo.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        correo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        correo.setToolTipText("Correo del cliente");
        correo.setMaximumSize(new java.awt.Dimension(195, 35));
        correo.setMinimumSize(new java.awt.Dimension(195, 35));
        correo.setPreferredSize(new java.awt.Dimension(195, 35));
        getContentPane().add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 172, -1, -1));

        nombreValidoLabel.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        nombreValidoLabel.setText("   ");
        nombreValidoLabel.setMaximumSize(new java.awt.Dimension(150, 35));
        nombreValidoLabel.setMinimumSize(new java.awt.Dimension(150, 35));
        nombreValidoLabel.setPreferredSize(new java.awt.Dimension(150, 35));
        getContentPane().add(nombreValidoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 133, -1, -1));

        correoValidoLabel.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        correoValidoLabel.setText("   ");
        correoValidoLabel.setMaximumSize(new java.awt.Dimension(150, 35));
        correoValidoLabel.setMinimumSize(new java.awt.Dimension(150, 35));
        correoValidoLabel.setPreferredSize(new java.awt.Dimension(150, 35));
        getContentPane().add(correoValidoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 173, -1, -1));

        telefonoValidoLabel.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        telefonoValidoLabel.setText("   ");
        telefonoValidoLabel.setMaximumSize(new java.awt.Dimension(150, 35));
        telefonoValidoLabel.setMinimumSize(new java.awt.Dimension(150, 35));
        telefonoValidoLabel.setPreferredSize(new java.awt.Dimension(150, 35));
        getContentPane().add(telefonoValidoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 213, -1, -1));

        direccionValidaLabel.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        direccionValidaLabel.setText("   ");
        direccionValidaLabel.setMaximumSize(new java.awt.Dimension(150, 35));
        direccionValidaLabel.setMinimumSize(new java.awt.Dimension(150, 35));
        direccionValidaLabel.setPreferredSize(new java.awt.Dimension(150, 35));
        getContentPane().add(direccionValidaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 253, -1, -1));

        fondo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getOk()
    {
        return ok;
    }

    public JTextField getCorreo()
    {
        return correo;
    }

    public JLabel getCorreoValidoLabel()
    {
        return correoValidoLabel;
    }

    public JTextField getDireccion()
    {
        return direccion;
    }

    public JLabel getDireccionValidaLabel()
    {
        return direccionValidaLabel;
    }

    public JTextField getNombre()
    {
        return nombre;
    }

    public JLabel getNombreValidoLabel()
    {
        return nombreValidoLabel;
    }

    public JTextField getTelefono()
    {
        return telefono;
    }

    public JLabel getTelefonoValidoLabel()
    {
        return telefonoValidoLabel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField correo;
    private javax.swing.JLabel correoLabel;
    private javax.swing.JLabel correoValidoLabel;
    private javax.swing.JTextField direccion;
    private javax.swing.JLabel direccionLabel;
    private javax.swing.JLabel direccionValidaLabel;
    private javax.swing.JLabel fondo;
    private javax.swing.JTextField nombre;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JLabel nombreValidoLabel;
    private javax.swing.JButton ok;
    private javax.swing.JTextField telefono;
    private javax.swing.JLabel telefonoLabel;
    private javax.swing.JLabel telefonoValidoLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
