/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sw.view;

import com.sw.controller.CellRenderer;
import com.sw.controller.TableHeaderRenderer;
import javax.swing.JButton;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Mohammed
 */
public class PrendasInterfaz extends javax.swing.JFrame
{

    /**
     * Creates new form PrendasInterfaz
     */
    public PrendasInterfaz()
    {
        initMyComponents();

        initComponents();

        renderTables();

    }

    private void initMyComponents()
    {

        tipoPrenda = new JButton("tshirt.ico");
        eliminar = new JButton("delete.ico");

    }

    private void renderTables()
    {

        tablaPrendas.setDefaultRenderer(Object.class, new CellRenderer());
        JTableHeader jTableHeader = tablaPrendas.getTableHeader();
        jTableHeader.setDefaultRenderer(new TableHeaderRenderer());
        tablaPrendas.setTableHeader(jTableHeader);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        scrollPrendas = new javax.swing.JScrollPane();
        tablaPrendas = new javax.swing.JTable();
        addPrenda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        totalKg = new javax.swing.JTextField();
        totalPrecio = new javax.swing.JTextField();
        totalPiezas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("test1");
        setMaximumSize(new java.awt.Dimension(595, 710));
        setMinimumSize(new java.awt.Dimension(595, 710));
        setName("prendasInterfaz"); // NOI18N
        setPreferredSize(new java.awt.Dimension(595, 710));
        setResizable(false);

        scrollPrendas.setMaximumSize(new java.awt.Dimension(575, 570));
        scrollPrendas.setMinimumSize(new java.awt.Dimension(575, 570));
        scrollPrendas.setPreferredSize(new java.awt.Dimension(575, 570));

        tablaPrendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, tipoPrenda, null, eliminar},
                {null, tipoPrenda, null, eliminar},
                {null, tipoPrenda, null, eliminar},
                {null, tipoPrenda, null, eliminar},
                {null, tipoPrenda, null, eliminar},
                {null, tipoPrenda, null, eliminar},
                {null, tipoPrenda, null, eliminar},
                {null, tipoPrenda, null, eliminar},
                {null, tipoPrenda, null, eliminar},
                {null, tipoPrenda, null, eliminar},
                {null, tipoPrenda, null, eliminar},
                {null, tipoPrenda, null, eliminar},
                {null, tipoPrenda, null, eliminar},
                {null, tipoPrenda, null, eliminar},
                {null, tipoPrenda, null, eliminar}
            },
            new String []
            {
                "Prenda", "Tipo de prenda", "Cantidad (piezas)", "Eliminar"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Object.class, Object.class, java.lang.Integer.class, Object.class
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }
        });
        scrollPrendas.setViewportView(tablaPrendas);

        addPrenda.setText("add.ico");
        addPrenda.setMaximumSize(new java.awt.Dimension(100, 80));
        addPrenda.setMinimumSize(new java.awt.Dimension(100, 80));

        jLabel1.setText("Total kg.");

        jLabel2.setText("Precio total.");

        jLabel3.setText("Total piezas.");

        totalKg.setText("Total kg...");
        totalKg.setEnabled(false);

        totalPrecio.setText("Precio total...");
        totalPrecio.setEnabled(false);

        totalPiezas.setText("Total piezas...");
        totalPiezas.setEnabled(false);
        totalPiezas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                totalPiezasActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("logo.img");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(totalPiezas, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(37, 37, 37))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(21, 21, 21)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(totalKg)
                                    .addComponent(totalPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(addPrenda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollPrendas, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addPrenda, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(totalKg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(totalPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(totalPiezas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(scrollPrendas, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalPiezasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_totalPiezasActionPerformed
    {//GEN-HEADEREND:event_totalPiezasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalPiezasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(PrendasInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
        {
            new PrendasInterfaz().setVisible(true);

        });

    }

    private JButton tipoPrenda;
    private JButton eliminar;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPrenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane scrollPrendas;
    private javax.swing.JTable tablaPrendas;
    private javax.swing.JTextField totalKg;
    private javax.swing.JTextField totalPiezas;
    private javax.swing.JTextField totalPrecio;
    // End of variables declaration//GEN-END:variables
}
