package com.sw.view;

import com.sw.controller.PrendasController;
import com.sw.utilities.Utilities;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Mohammed
 */
public class PrendasInterfaz extends javax.swing.JFrame
{

    public PrendasInterfaz()
    {
        initMyComponents();

        initComponents();

        new PrendasController(this);

    }

    private void initMyComponents()
    {

        tipoPrenda = new ArrayList<>();
        eliminar = new ArrayList<>();

        for (int i = 0; i < 10; i++)
        {
            tipoPrenda.add(new JButton(Utilities.getIcon("/com/src/images/tshirt.png")));
            eliminar.add(new JButton(Utilities.getIcon("/com/src/images/delete.png")));

        }

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        scrollPrendas = new javax.swing.JScrollPane();
        prendas = new javax.swing.JTable();
        addPrenda = new javax.swing.JButton();
        totalKgLabel = new javax.swing.JLabel();
        precioTotalLabel = new javax.swing.JLabel();
        piezasLabel = new javax.swing.JLabel();
        totalKg = new javax.swing.JTextField();
        totalPrecio = new javax.swing.JTextField();
        totalPiezas = new javax.swing.JTextField();
        logo = new javax.swing.JLabel();
        editarPrenda = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Añadir prendas");
        setMinimumSize(new java.awt.Dimension(579, 700));
        setName("prendasInterfaz"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrollPrendas.setMaximumSize(new java.awt.Dimension(575, 550));
        scrollPrendas.setMinimumSize(new java.awt.Dimension(575, 550));
        scrollPrendas.setPreferredSize(new java.awt.Dimension(575, 550));

        prendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},

            },
            new String []
            {
                null, null, null, null
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Object.class, Object.class, java.lang.Integer.class, Object.class
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }
        });
        scrollPrendas.setViewportView(prendas);

        getContentPane().add(scrollPrendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, 550));

        addPrenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/add.png"))); // NOI18N
        addPrenda.setToolTipText("Añadir nueva prenda");
        addPrenda.setMaximumSize(new java.awt.Dimension(100, 80));
        addPrenda.setMinimumSize(new java.awt.Dimension(100, 80));
        getContentPane().add(addPrenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 100, 40));

        totalKgLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalKgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/kilos.png"))); // NOI18N
        totalKgLabel.setText(" Total kg        :");
        totalKgLabel.setMaximumSize(new java.awt.Dimension(105, 25));
        totalKgLabel.setMinimumSize(new java.awt.Dimension(105, 25));
        totalKgLabel.setPreferredSize(new java.awt.Dimension(105, 25));
        getContentPane().add(totalKgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        precioTotalLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        precioTotalLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/precio.png"))); // NOI18N
        precioTotalLabel.setText(" Precio total   :");
        precioTotalLabel.setMaximumSize(new java.awt.Dimension(105, 25));
        precioTotalLabel.setMinimumSize(new java.awt.Dimension(105, 25));
        precioTotalLabel.setPreferredSize(new java.awt.Dimension(105, 25));
        getContentPane().add(precioTotalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        piezasLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        piezasLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/tshirt.png"))); // NOI18N
        piezasLabel.setText(" Piezas           :");
        piezasLabel.setMaximumSize(new java.awt.Dimension(105, 25));
        piezasLabel.setMinimumSize(new java.awt.Dimension(105, 25));
        piezasLabel.setPreferredSize(new java.awt.Dimension(105, 25));
        getContentPane().add(piezasLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        totalKg.setText("Total kg...");
        totalKg.setEnabled(false);
        getContentPane().add(totalKg, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 100, -1));

        totalPrecio.setText("Precio total...");
        totalPrecio.setEnabled(false);
        getContentPane().add(totalPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 100, -1));

        totalPiezas.setText("Total piezas...");
        totalPiezas.setEnabled(false);
        getContentPane().add(totalPiezas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 100, -1));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/logo.jpg"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 230, -1));

        editarPrenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/edit.png"))); // NOI18N
        editarPrenda.setToolTipText("Editar prenda");
        editarPrenda.setMaximumSize(new java.awt.Dimension(100, 40));
        editarPrenda.setMinimumSize(new java.awt.Dimension(100, 40));
        editarPrenda.setPreferredSize(new java.awt.Dimension(100, 40));
        getContentPane().add(editarPrenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 100, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/fondo.jpg"))); // NOI18N
        fondo.setMaximumSize(new java.awt.Dimension(600, 700));
        fondo.setMinimumSize(new java.awt.Dimension(600, 700));
        fondo.setPreferredSize(new java.awt.Dimension(600, 700));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public ArrayList<JButton> getTipoPrenda()
    {
        return tipoPrenda;
    }

    public ArrayList<JButton> getEliminar()
    {
        return eliminar;
    }

    public JButton getAddPrenda()
    {
        return addPrenda;
    }

    public JButton getEditarPrenda()
    {
        return editarPrenda;
    }

    public JTable getPrendasTable()
    {
        return prendas;
    }

    public JTextField getTotalKg()
    {
        return totalKg;
    }

    public JTextField getTotalPiezas()
    {
        return totalPiezas;
    }

    public JTextField getTotalPrecio()
    {
        return totalPrecio;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(PrendasInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
        {

            PrendasInterfaz prendas = new PrendasInterfaz();

            prendas.setVisible(true);
            prendas.setLocationRelativeTo(null);

        });

    }

    private ArrayList<JButton> tipoPrenda;
    private ArrayList<JButton> eliminar;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPrenda;
    private javax.swing.JButton editarPrenda;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel piezasLabel;
    private javax.swing.JLabel precioTotalLabel;
    private javax.swing.JTable prendas;
    private javax.swing.JScrollPane scrollPrendas;
    private javax.swing.JTextField totalKg;
    private javax.swing.JLabel totalKgLabel;
    private javax.swing.JTextField totalPiezas;
    private javax.swing.JTextField totalPrecio;
    // End of variables declaration//GEN-END:variables
}
