package com.sw.view;

import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author Me
 */
public class TiposPrendasInterfaz extends javax.swing.JFrame
{

    public TiposPrendasInterfaz()
    {

        initWindow();

        initComponents();

        initMyComponents();

    }

    private void initWindow()
    {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            System.out.println(ex.getMessage());
        }
        //</editor-fold>

    }

    private void initMyComponents()
    {
        eliminar = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        logo = new javax.swing.JLabel();
        editar = new javax.swing.JButton();
        anadir = new javax.swing.JButton();
        scrollTipoPrendas = new javax.swing.JScrollPane();
        tiposPrendas = new javax.swing.JTable();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tipos prendas");
        setMaximumSize(new java.awt.Dimension(495, 650));
        setMinimumSize(new java.awt.Dimension(495, 650));
        setPreferredSize(new java.awt.Dimension(495, 650));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/logo.jpg"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/edit.png"))); // NOI18N
        editar.setToolTipText("Editar prenda");
        editar.setActionCommand("editTipoPrenda");
        editar.setMaximumSize(new java.awt.Dimension(100, 45));
        editar.setMinimumSize(new java.awt.Dimension(100, 45));
        editar.setPreferredSize(new java.awt.Dimension(100, 45));
        getContentPane().add(editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        anadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/add.png"))); // NOI18N
        anadir.setToolTipText("Añadir nueva prenda");
        anadir.setActionCommand("addTipoPrenda");
        anadir.setMaximumSize(new java.awt.Dimension(100, 45));
        anadir.setMinimumSize(new java.awt.Dimension(100, 45));
        anadir.setPreferredSize(new java.awt.Dimension(100, 45));
        getContentPane().add(anadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        scrollTipoPrendas.setMaximumSize(new java.awt.Dimension(490, 485));
        scrollTipoPrendas.setMinimumSize(new java.awt.Dimension(490, 485));
        scrollTipoPrendas.setPreferredSize(new java.awt.Dimension(490, 485));

        tiposPrendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null},

            },
            new String []
            {
                "Title 1", "Title 2"
            }
        ));
        scrollTipoPrendas.setViewportView(tiposPrendas);

        getContentPane().add(scrollTipoPrendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public ArrayList<JButton> getEliminar()
    {
        return eliminar;
    }

    public JButton getAnadir()
    {
        return anadir;
    }

    public JButton getEditar()
    {
        return editar;
    }

    public JTable getTiposPrendasTable()
    {
        return tiposPrendas;
    }

    private ArrayList<JButton> eliminar;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anadir;
    private javax.swing.JButton editar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel logo;
    private javax.swing.JScrollPane scrollTipoPrendas;
    private javax.swing.JTable tiposPrendas;
    // End of variables declaration//GEN-END:variables
}
