package com.sw.view;

/**
 *
 * @author Mohammed
 */
public class TiposPrendas extends javax.swing.JFrame
{

    public TiposPrendas()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        logo = new javax.swing.JLabel();
        editar = new javax.swing.JButton();
        anadir = new javax.swing.JButton();
        scrollTipoPrendas = new javax.swing.JScrollPane();
        tiposPrendas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tipos prendas");
        setMaximumSize(new java.awt.Dimension(495, 675));
        setMinimumSize(new java.awt.Dimension(495, 675));
        setPreferredSize(new java.awt.Dimension(495, 675));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/logo.jpg"))); // NOI18N
        logo.setMaximumSize(new java.awt.Dimension(215, 95));
        logo.setMinimumSize(new java.awt.Dimension(215, 95));
        logo.setPreferredSize(new java.awt.Dimension(215, 95));
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/edit.png"))); // NOI18N
        editar.setMaximumSize(new java.awt.Dimension(100, 30));
        editar.setMinimumSize(new java.awt.Dimension(100, 30));
        editar.setPreferredSize(new java.awt.Dimension(100, 30));
        getContentPane().add(editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        anadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/add.png"))); // NOI18N
        anadir.setMaximumSize(new java.awt.Dimension(100, 30));
        anadir.setMinimumSize(new java.awt.Dimension(100, 30));
        anadir.setPreferredSize(new java.awt.Dimension(100, 30));
        getContentPane().add(anadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        tiposPrendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null},

            },
            new String []
            {
                "Title 1", "Title 2"
            }
        ));
        scrollTipoPrendas.setViewportView(tiposPrendas);

        getContentPane().add(scrollTipoPrendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 490, 490));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/images/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(TiposPrendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
        {
            new TiposPrendas().setVisible(true);

        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anadir;
    private javax.swing.JButton editar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logo;
    private javax.swing.JScrollPane scrollTipoPrendas;
    private javax.swing.JTable tiposPrendas;
    // End of variables declaration//GEN-END:variables
}
