/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sw.view;

import com.sw.controller.CellRenderer;
import com.sw.controller.TableHeaderRenderer;
import javax.swing.JButton;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Mohammed
 */
public class VistaPrincipal extends javax.swing.JFrame
{

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal()
    {

        initMyComponents();

        initComponents();

        initTables();

    }

    private void initMyComponents()
    {
        verPrendas = new JButton("Ver prendas");
        moverLavado = new JButton("Mover a lavando");
        eliminar = new JButton("Eliminar");

    }

    private void initTables()
    {

        tablaEnCola.setDefaultRenderer(Object.class, new CellRenderer());
        JTableHeader jTableHeader = tablaEnCola.getTableHeader();
        jTableHeader.setDefaultRenderer(new TableHeaderRenderer());
        tablaEnCola.setTableHeader(jTableHeader);

        jTableHeader = tablaEnProceso.getTableHeader();
        jTableHeader.setDefaultRenderer(new TableHeaderRenderer());
        tablaEnProceso.setDefaultRenderer(Object.class, new CellRenderer());
        tablaEnProceso.setTableHeader(jTableHeader);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        scrollTablaEnCola = new javax.swing.JScrollPane();
        tablaEnCola = new javax.swing.JTable();
        scrollTablaEnProceso = new javax.swing.JScrollPane();
        tablaEnProceso = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(1230, 800));
        setMinimumSize(new java.awt.Dimension(1230, 800));
        setPreferredSize(new java.awt.Dimension(1230, 800));

        jButton1.setText("new service");
        jButton1.setMaximumSize(new java.awt.Dimension(200, 75));
        jButton1.setMinimumSize(new java.awt.Dimension(200, 75));
        jButton1.setPreferredSize(new java.awt.Dimension(200, 100));

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(1180, 700));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1180, 700));

        scrollTablaEnCola.setBackground(new java.awt.Color(204, 204, 204));

        tablaEnCola.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, verPrendas, null, null, moverLavado, eliminar},
                {null, verPrendas, null, null, moverLavado, eliminar},
                {null, verPrendas, null, null, moverLavado, eliminar},
                {null, verPrendas, null, null, moverLavado, eliminar},
                {null, verPrendas, null, null, moverLavado, eliminar}

            },
            new String []
            {
                "Cliente", "Prendas", "Kilos", "Total", "Añadir a lavado", "Eliminar"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.Object.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class, Object.class
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            @Override
            public boolean isCellEditable(int row, int column)
            {
                return false;
            }

        });
        tablaEnCola.setRowHeight(25);
        tablaEnCola.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                tablaEnColaMouseClicked(evt);
            }
        });
        scrollTablaEnCola.setViewportView(tablaEnCola);

        jTabbedPane1.addTab("En cola", null, scrollTablaEnCola, "Conjunto de prendas que está en la cola.");

        scrollTablaEnProceso.setBackground(new java.awt.Color(204, 204, 204));

        tablaEnProceso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, verPrendas, null, null, null, eliminar},
                {null, verPrendas, null, null, null, eliminar},
                {null, verPrendas, null, null, null, eliminar},
                {null, verPrendas, null, null, null, eliminar}

            },
            new String []
            {
                "Cliente", "Prendas", "Kilos", "Tiempo estimado", "Pasar a terminado", "Eliminar"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.Object.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class, Object.class
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            @Override
            public boolean isCellEditable(int row, int column)
            {
                return false;
            }

        }
    );
    scrollTablaEnProceso.setViewportView(tablaEnProceso);

    jTabbedPane1.addTab("En proceso", scrollTablaEnProceso);
    jTabbedPane1.addTab("Terminado", jScrollPane3);

    jTextField2.setText("Buscar...");

    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Aquí habrá un logo...");

    jLabel2.setText("search.icon");

    jMenu1.setText("Configuración");
    jMenuBar1.add(jMenu1);

    jMenu2.setText("Utilidades");
    jMenuBar1.add(jMenu2);

    jMenu3.setText("Misceláneos");
    jMenuBar1.add(jMenu3);

    jMenu4.setText("Juegos");

    jMenuItem1.setText("CrazyCubes");
    jMenuItem1.setToolTipText("CrazyCubes");
    jMenuItem1.addActionListener(new java.awt.event.ActionListener()
    {
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            jMenuItem1ActionPerformed(evt);
        }
    });
    jMenu4.add(jMenuItem1);

    jMenuBar1.add(jMenu4);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel2)
                    .addGap(70, 70, 70)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(0, 0, 0)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaEnColaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_tablaEnColaMouseClicked
    {//GEN-HEADEREND:event_tablaEnColaMouseClicked
        int column = tablaEnCola.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tablaEnCola.getRowHeight();

        if (row < tablaEnCola.getRowCount() && row >= 0 && column < tablaEnCola.getColumnCount() && column >= 0)
        {
            Object value = tablaEnCola.getValueAt(row, column);

            if (value instanceof JButton)
            {
                ((JButton) value).doClick();
                System.out.println("Hola");
            }

        }

    }//GEN-LAST:event_tablaEnColaMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem1ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->
        {

            VistaPrincipal vistaPrincipal = new VistaPrincipal();

            vistaPrincipal.setVisible(true);
            vistaPrincipal.setLocationRelativeTo(null);

        });

    }

    private JButton verPrendas;
    private JButton moverLavado;
    private JButton eliminar;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JScrollPane scrollTablaEnCola;
    private javax.swing.JScrollPane scrollTablaEnProceso;
    private javax.swing.JTable tablaEnCola;
    private javax.swing.JTable tablaEnProceso;
    // End of variables declaration//GEN-END:variables
}
